FROM python:3.11-slim

WORKDIR /usr/src/app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get install -y netcat-openbsd && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /usr/src/app/
RUN pip install --upgrade pip

RUN pip install -r requirements.txt

COPY . /usr/src/app/

COPY ./entrypoint.sh /usr/src/app/

RUN chmod +x entrypoint.sh

ENTRYPOINT ["./entrypoint.sh"]